### ISSUE TITLE
加油！

### ISSUE THREAD

**Issue by I-am-Yu** [kaich/Yuedu#1]

**Comment by siseboy** [comment]
期待什么时候可以测试？重度看小说用户

**Comment by kaich** [comment]
@siseboy 最早应该4.20号左右吧，先能看，后面逐渐完善。

**Comment by cantwork** [comment]
> @siseboy 最早应该4.20号左右吧，先能看，后面逐渐完善。

我看简介更新了，是已经在AppStore上架了么？

**Comment by kaich** [comment]
@cantwork 并没有，还有几个麻烦的细节需要修复和完善，我尽快先出个bata版（你们边使用我边修复问题）

**Comment by siseboy** [comment]
盼星星盼月亮咯~~~现在 ios 和 Android 不同软件，交替看小说的时候不能同步好痛苦。

**Comment by kaich** [comment]
目前上架了初步测试版
