### ISSUE TITLE
听书功能听完一章就结束了

### ISSUE THREAD

**Issue by Ylightooo** [kaich/Yuedu#11]
很好用，虽然打开书的速度又慢，目录没加载出来会闪退，翻页设置又有点问题，但好用啊，同类软件已删，慢慢等更新
edge朗读xiaoxiao的发音yyds

**Comment by kaich** [comment]
为啥有的反馈打开有点慢，我这边基本打开都是秒开啊。 是用的源太慢了吧？

翻页设置什么问题？ （漫画模式翻页切换是无效的）

**Comment by liuqi875208734** [comment]
点左上角听书是反应会慢一点，然后听书挂后台，息屏软件就崩溃了

**Comment by kaich** [comment]
@liuqi875208734 等下个版本听书才做完，目前是为了发版本修复一些其他问题。QQ群公告有写每个版本的主要目标。

**Comment by Ylightooo** [comment]
就普通模式下，设置的翻页区域不灵，最左下角那一列始终是点击触发上一页。
更新后，小说打开的速度变快了，上个版本还是先缓存后才感觉快些。
PS.长按最下面一排退出阅读界面经常触发home条，每次按下去都有点发虚😂，要是触发区域更大点就好了，或者上滑退出
