### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by yygutn** [kaich/Yuedu#14]
1. 在最后一页翻页时添加提示，退出阅读
2. 电池/时间/章节等信息放在最上面

**Comment by kaich** [comment]
1. 后面可以添加
2. 电池/时间/章节可自定义

**Comment by huangfengye** [comment]
> 1. 后面可以添加
> 2. 电池/时间/章节可自定义

建议参考下爱阅书香的设计。 很看好你的阅读ios版

**Comment by uclort** [comment]
@kaich 希望可以增加阅读页上滑退出阅读的手势，也是可以参考爱阅书香。

**Comment by kaich** [comment]
已添加 `最后一页翻页时添加提示`
