### ISSUE TITLE
阅读的BUG

### ISSUE THREAD

**Issue by a1029602653** [kaich/Yuedu#15]
在阅读的时候，有些段落会显示不全，无论是仿真翻页还是滚动，都有此BUG，非常影响阅读
![image](https://user-images.githubusercontent.com/39894592/120090348-4a10b080-c134-11eb-9cd8-0944ec0d51e9.png)

**Comment by a1029602653** [comment]
就跟图上的那段一样

**Comment by kaich** [comment]
请详细描述， 什么源 什么书 多少页

**Comment by kaich** [comment]
长时间没有详细描述，自动关闭
