### ISSUE TITLE
关于竖屏模式下的bug反馈

### ISSUE THREAD

**Issue by eachann1026** [kaich/Yuedu#16]
>  `竖屏翻页` 目录选择章节，上滑到上一章就会卡住，不管再怎么上下滑动都会是上一章的内容，而且还会出现文字被遮挡的问题

https://share.icloud.com/photos/0s4jcC1HMkfSQ4zp6FSYqBNYg

**Comment by eachann1026** [comment]
![01336CDC-E6F9-4792-BEA4-D79653891BD0](https://user-images.githubusercontent.com/43348055/120655192-ffd15b80-c4b4-11eb-9733-e54ddcdfd297.png)
正常阅读下  上下滑动 文字被遮挡了

**Comment by eachann1026** [comment]
上一个问题并没有解决  [上一个问题](https://github.com/kaich/Yuedu/issues/9)

视频链接
https://share.icloud.com/photos/0SB8kzFPiPzdtUEyOZGx00YlA

**Comment by eachann1026** [comment]
还有更换字体后，下一章和上一章还是原来的字体呀

**Comment by eachann1026** [comment]
竖屏情况下点击下一页会滚动过头

https://share.icloud.com/photos/0kf8bQFaKPV_T_OUaiMnR7oSA

**Comment by kaich** [comment]
发了新版本可以试一下

**Comment by eachann1026** [comment]
还有叠字的问题，选择目录向上滑动不连贯的问题

> 顺便问一个最重要的问题，怎么才可以全屏下一页，点击屏幕中间出现菜单，不管我怎么设置都不行

**Comment by kaich** [comment]
选择目录问题目前不处理

**Comment by kaich** [comment]
更新1.2.4, 看看还有没有文字截断问题？
