### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by wicatfly** [kaich/Yuedu#23]
作者你好，我个人对功能倒是没有更多的需求，只希望 UI 可以继承 iOS 的风格精致些，阅读界面上下导航栏偏安卓了，跟爱阅书香没啥区别，花火阅读的 UI 倒是不错，还请考虑

**Comment by kaich** [comment]
偏安卓？ 你看下iOS系统软件，哪个不是上下导航？！

**Comment by wicatfly** [comment]
> 偏安卓？ 你看下iOS系统软件，哪个不是上下导航？！

抱歉，表达不清让你误会了，不是做成上下导航就是安卓，而是上下导航的风格，我也不知道怎么表达了 🤝

**Comment by kaich** [comment]
可以结合图片详细描述下，方便理解

**Comment by wicatfly** [comment]
> 可以结合图片详细描述下，方便理解

我想提几条具体建议，希望能够得到接纳，谢谢（不懂专业术语，不要笑话我哈）

1 阅读状态下，单击后弹出的上下导航栏在外沿添加一条阴影或者外沿用颜色点缀下，这样导航栏稍微立体些，好看
2 阅读状态下，下导航栏隐藏图标的文字
3 阅读状态下，提供隐藏全屏等模式按钮、明亮模式按钮和听书按钮的选项
4 阅读状态下，可以隐藏左右下角上一章下一章的按钮，以及左上角的章节和网址
5 书架中，取消角标，改为在书名下换行显示未读章节、更新的章节

**Comment by wicatfly** [comment]
我想提几条具体建议，希望能够得到接纳，谢谢（不懂专业术语，不要笑话我哈）

1 阅读状态下，单击后弹出的上下导航栏在外沿添加一条阴影或者外沿用颜色点缀下，这样导航栏稍微立体些，好看
2 阅读状态下，下导航栏隐藏图标的文字
3 阅读状态下，提供隐藏全屏等模式按钮、明亮模式按钮和听书按钮的选项
4 阅读状态下，可以隐藏左右下角上一章下一章的按钮，以及左上角的章节和网址
5 书架中，取消角标，改为在书名下换行显示未读章节、更新的章节
2021年6月28日 +0800 14:27 kai cheng ，写道：
