### ISSUE TITLE
无法把书籍加入书架

### ISSUE THREAD

**Issue by huangfengye** [kaich/Yuedu#24]
**问题描述**
无法把书籍加入书架

**重现步骤**

搜索到书籍后，添加到书架按钮无法使用。按开始阅读，再点左上角返回，提示是否加入到书架，点加入书架后，同样不起作用。

**测试环境**
 - 设备型号: [e.g. iPhone X]
 - 系统: [e.g. iOS14.3]
 - 书源: [任意书源]
 - 版本: [tf版本1.2.7（24）]

**Comment by kaich** [comment]
老版本升级起来的，卸载重装！
