### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by noir1216** [kaich/Yuedu#26]
朗读模式语句定位。就是像安卓那些能显示具体读到了哪一句

还有就是要是能添加谷歌tts支持就好了，因为习惯了安卓上用谷歌的tts来听书。
之前自己在爱阅书香上尝试使用自定义语音库添加谷歌tts的api，但未成功，具体参数代码不会填。如果作者能适配一下就好了（自己的一点奢望吧）

**Comment by kaich** [comment]
具体读到哪一句，作用不大，目前应该不会做（很多其他的功能要做）。

现在都有语音管理模块，自己可以看下阅读的规则，直接写请求。 

话说这些Key，这么贵你们都自己买？

**Comment by kaich** [comment]
如果需要预置这种API，方便的话，是否可以token， key 等参数提供一下，方便测试
