### ISSUE TITLE
希望可以显示章节名称

### ISSUE THREAD

**Issue by uclort** [kaich/Yuedu#27]
**功能详细描述.**
现在有显示章节的功能，但是只显示第几章

**描述你想要的解决方案**
希望可以带上名称

**附加信息**
![image](https://user-images.githubusercontent.com/17818831/127664797-9f052114-6c42-4f4c-97cc-e51a31e0309a.jpeg)

**Comment by kaich** [comment]
有的章节太长了，不会带
