### ISSUE TITLE
是否会降低系统要求

### ISSUE THREAD

**Issue by tsukiikekaoru** [kaich/Yuedu#28]
手持老设备，系统停在ios12了，不知道是否用了新系统才有的API，致使无法兼容ios13以下的系统。如果可能，还是希望能用上阅读，在安卓上真的是很不错的一款软件，ios这样的太少了。

**Comment by kaich** [comment]
应该不会，适配起来太麻烦了，而且用户少。目前要做的东西太多了，应该不会花大量时间去做这种事情。
