### ISSUE TITLE
搜索后加载书籍列表会闪退，创建净化规则保存后再进入 净化规则列表为空

### ISSUE THREAD

**Issue by cantwork** [kaich/Yuedu#3]
搜索闪退不是立即的，大概三五秒之后，进入书籍详情页也会这样
净化规则在创建一条新规则后能看见之前保存的规则，退出后再进入规则列表就都不见了
iphone12
ios 14.5.1

**Comment by kaich** [comment]
目前有些源没有问题，有些源有问题，最好粘贴书源，方便我调试

**Comment by cantwork** [comment]
> 目前有些源没有问题，有些源有问题，最好粘贴书源，方便我调试

难怪，我直接用的阅读3.0的189个精品源 https://celeter.github.io/SourceGo/book_source/all.json
单个源试了下是ok的

**Comment by kaich** [comment]
@cantwork 这个源的搜索崩溃问题解决了，这两天会再发个版本

**Comment by kaich** [comment]
1.1版本晚点可更新，修复以上提到的问题。
