### ISSUE TITLE
可以在Mac上安装吗

### ISSUE THREAD

**Issue by haitang-blossoms** [kaich/Yuedu#30]
**功能详细描述.**
希望能通过Mac app store把源阅读安装在Mac上。

**描述你想要的解决方案**
不确定过程是怎么样，但是因为都是Apple Silicon芯片应该不需要修改代码什么的，所以应该只需要标记能在“运行 macOS 11.0 或更高版本的系统并装有 Apple M1 芯片的 Mac”就行了。

**附加信息**
如果可以支持Mac那就非常感谢！

**Comment by kaich** [comment]
不行的吧，我也没有M1的电脑，APP还有要做的事情太多了，目前不在考虑范围内。
