### ISSUE TITLE
关于源仓库里真白萌书源登陆后无法搜索

### ISSUE THREAD

**Issue by panyuhang93** [kaich/Yuedu#33]
**问题描述**
这个源需要登录，但是我登录之后发现还是搜索不到，Android上可以的，(另外似乎不能进行批量数源禁用盒书源分组管理啊)

**重现步骤**

**期望结果**
对你期望发生的事情的清晰而简明的描述。

**截图**
如果可以的话，添加屏幕截图来帮助解释您的问题。

**测试环境**
 - 设备型号: iphone se 2
 - 系统: ios 14.4
 - 书源: 源仓库里的真白萌
 - 版本: 1.3.6

**附加信息**
在这里添加关于这个问题的其他内容。

> 请按照模板详细描述问题的内容，否则问题难以理解和重现，不会对此问题进行任何回复

**Comment by kaich** [comment]
有没有测试账号啊，我测试下

**Comment by kaich** [comment]
新版已解决

**Comment by panyuhang93** [comment]
实在感谢，之前没看见，不好意思

**Comment by panyuhang93** [comment]
呃，试了试无法拉去书籍信息，看不了
