### ISSUE TITLE
关于ios导入字体显示 “导入字体失败” 的问题

### ISSUE THREAD

**Issue by Wa-Fe** [kaich/Yuedu#34]
ios导入字体失败
1，测试的字体文件网址是 [https://m.diqibu.com/font/1256.html](url) 
2，源阅读版本为1.3.6
3，ios版本为 iPhone 11，ios14.7.1

第一种导入的方式是先把字体下载到本地，通过mac自带的隔空投送发送到ios,打开方式直接选择`源阅读`，显示 `导入字体失败`
第二种方式是通过Safari浏览器下载字体，通过共享的方式导入字体，还是显示`导入字体失败`

通过搜索了解到部分文章说要先把字体通过描述文件安装到本地，之后可以在设置>通用>字体 查询到

所以尝试安装先把字体下载到手机，ios上通过 [https://apps.apple.com/cn/app/ifont-%E5%AD%97%E4%BD%93%E7%AE%A1%E7%90%86%E5%99%A8/id1496928666](url)  这个软件选择本地字体成描述文件再安装到手机，但是没有任何作用。无法在设置里面查询到字体的安装信息

不确定字体安装失败是iOS本身系统的问题还是什么问题

**Comment by kaich** [comment]
好的，我之后会试试。大概率是和系统/字体有关系... 有结果在回复你

**Comment by kaich** [comment]
字体看过了，这个字体在我的手机上可以导入，没有任何问题。应该并不是源阅读软件的原因。

**Comment by Wa-Fe** [comment]
我重新录制了一个操作流程，可以参考下。如果你那边还是没问题可能就是我这边的问题了。
链接：https://share.weiyun.com/dOuQ8cBK 密码：2stfx2

**Comment by kaich** [comment]
@Wa-Fe 就是这个流程的，没有问题
