### ISSUE TITLE
部分书籍只能看到封面

### ISSUE THREAD

**Issue by fqx** [kaich/Yuedu#35]
**问题描述**
《阿西莫夫科幻圣经银河帝国1-15大全集》这本书只能看到15个封面。
用epubsplit拆开后也只显示一页封面。

**重现步骤**

**期望结果**
应该可以看到书本内容。

**截图**
![IMG_A3436AF903BD-1](https://user-images.githubusercontent.com/5069773/129568776-16ec7c0f-0da6-419e-9128-d2e8630e7440.jpeg)

**测试环境**
 - 设备型号: iPhone 12
 - 系统: iOS 14.7.1
 - 书源: iCloud Drive
 - 版本: V1.3.6

**附加信息**
拆分开的书可以从这里下载。如果涉及版权可通知我删除。
https://www.dropbox.com/s/2vrbfi96f5k6k6h/Yin%20He%20Di%20Guo%205_Mai%20Xiang%20Ji%20Di%20-%20Ai%20Sa%20Ke%20_A%20Xi%20Mo%20Fu.epub?dl=0

> 请按照模板详细描述问题的内容，否则问题难以理解和重现，不会对此问题进行任何回复

**Comment by kaich** [comment]
是的，epub解析有问题，部分能看，部分书不行。暂时还没时间处理这个... 这个后面会处理

**Comment by kaich** [comment]
用现在的tf版试试，应该是可以了

**Comment by fqx** [comment]
@kaich tf版跟之前一样的

**Comment by kaich** [comment]
书发出来

**Comment by fqx** [comment]
@kaich 一楼就有啊

**Comment by kaich** [comment]
等下个tf版再试试

**Comment by kaich** [comment]
试试新版本的tf，应该可以了

**Comment by fqx** [comment]
@kaich 并没有。 1.4.4（87）

**Comment by kaich** [comment]
卸载重装，我这边是没问题了
