### ISSUE TITLE
阿里云音源参数简化

### ISSUE THREAD

**Issue by minoism** [kaich/Yuedu#39]
阿里的音源建议改成或者增加`AccessKeyId`和`AccessKeySecret`参数模式，因为阿里的token几天就会变一次，每天去复制新的再修改很麻烦，id和secret可以用sdk获取token，这样会舒服很多

获取 Token 的 SDK
https://help.aliyun.com/document_detail/72153.htm?spm=a2c4g.11186623.0.0.762618195dqZeK#title-j7l-clf-hgy

**Comment by kaich** [comment]
后面再弄吧，上线了那么久，基本没有人提这方面的问题。用的人太少，放到之后再弄

**Comment by kaich** [comment]
下个正式版会加上...

**Comment by minoism** [comment]
坐等！！一直就等着这个功能了
