### ISSUE TITLE
无法阅读，体验不佳

### ISSUE THREAD

**Issue by siseboy** [kaich/Yuedu#4]
iphone7

ios 14.5.1

1、数据和阅读3.0不互通，无法使用阅读3.0的备份数据。

还是很希望能和阅读3.0的数据互通的，这样ios和Android的阅读进度和书架都能同步。

2、书架点书籍进去后直接返回会一定几率会导致书架空白，清后台，或者添加新书后才能恢复。

3、无法在阅读界面直接换源。

4、设置翻页区域点击完成无提示，只能点击取消退出，但实际是已经保存设置的。

5、恢复备份后再备份，备份的数据里的backup文件夹会多层嵌套。

6、听书不正常，一直在朗读百分之多少。

**Comment by kaich** [comment]
好的谢谢反馈。

目前有些安卓方面的内容不兼容，因为安卓一直也在更新修改，目前集中测试处理各种源的问题，改动会比较频繁。

目前测试阶段改动会比较频繁，不会刻意去兼容安卓版本，先集中处理各种源的兼容问题。

换源是有问题的，目前这块不是主要核心，没有处理。先保证绝大部分源兼容问题。
 
安卓数据兼容会留在后面相对稳定的版本再去处理。

**Comment by kaich** [comment]
可更新1.1
