### ISSUE TITLE
显示不全

### ISSUE THREAD

**Issue by 576440127** [kaich/Yuedu#42]
**问题描述**

滚动翻页模式下，有时候两页链接的位置会显示不全，如缺一部分文字不显示或一行文字只显示一半，这个问题只有在4.7寸屏幕中才会出现，我用6s就经常有这个情况，换Max plus就没有，而且6s改成全屏模式阅读的时候就会都显示出来，只有普通模式下会这样

**重现步骤**

**期望结果**
对你期望发生的事情的清晰而简明的描述。

**截图**
![67442019-BF5A-481F-BACD-E4683C076639](https://user-images.githubusercontent.com/67869302/132047447-bbb515ae-098e-44ed-96a1-9597bdaa8e29.png)

**测试环境**
 - 设备型号: [e.g. iPhone6s]
 - 系统: [e.g. iOS14.6]
 - 书源: [e.g. stock browser, safari]
 - 版本: [e.g. 1.3.9]

**附加信息**
在这里添加关于这个问题的其他内容。

> 请按照模板详细描述问题的内容，否则问题难以理解和重现，不会对此问题进行任何回复

**Comment by kaich** [comment]
调整间距试试

**Comment by 576440127** [comment]
> 调整间距试试

暂时没有遇到，在碰到这个问题我试试

**Comment by 576440127** [comment]
> 调整间距试试

暂时没有遇到，在碰到这个问题我试试


> 调整间距试试

比较尴尬，我好像没有找到间距调整的地方，就找到一个小组件间距调整，好像不太对，调整这个只是调整小组件，对文字部分没有变化，还是一样的问题

**Comment by 576440127** [comment]
![mmexport1630943709579](https://user-images.githubusercontent.com/67869302/132242337-60d4d533-0f5d-416d-87ca-4df7a9c66d26.jpg)

**Comment by kaich** [comment]
自定义排版

**Comment by 576440127** [comment]
> 自定义排版

找到了，调整间距和字距后就显示完整了，谢谢
