### ISSUE TITLE
书籍详情页面加载缓慢

### ISSUE THREAD

**Issue by 0rzNuII** [kaich/Yuedu#43]
**问题描述**
某些书籍在进入详情页面后，就会加载很慢，一直转圈圈加载，其他所有操作都没法继续了。然后重启软件、网络和手机也没用。

![IMG_5430](https://user-images.githubusercontent.com/40875899/132189223-71ed8d93-504c-4bc0-836d-f3fa8a93446c.PNG)

**测试环境**
 - 设备型号: iPhone 11 pro max
 - 系统: iOS 14.7.1
 - 书源: N/A
 - 版本: V1.3.9

**Comment by kaich** [comment]
和源有关系，网站快它就快，网站慢他就慢

**Comment by 0rzNuII** [comment]
> 和源有关系，网站快它就快，网站慢他就慢

但是我安卓版用的一样的源，一样的书，安卓就加在很快，iOS就很慢……
书名《龙王传说》

**Comment by kaich** [comment]
那就把源发出来

**Comment by 0rzNuII** [comment]
> 那就把源发出来

emmmm刚刚卸载了，用安卓版本好了
