### ISSUE TITLE
语音引擎能将edge大声朗读的集成上吗?

### ISSUE THREAD

**Issue by 3594302** [kaich/Yuedu#44]
微软edge的大声朗读在线合成语音效果比较好,
能否集成上

**Comment by kaich** [comment]
自己找找阅读有没有人做这个语音源。已经提供自己添加的功能了

**Comment by Jarvis110469** [comment]
> 微软edge的大声朗读在线合成语音效果比较好, 能否集成上

最新的testflight版本已经支持了 自己去azune注册个key就可以用啦
