### ISSUE TITLE
V1.4.1 版本无法缓存书籍，在线阅读翻下一章总是会出现“内容为空”的情况

### ISSUE THREAD

**Issue by xjiabin** [kaich/Yuedu#47]
**问题描述**
1. V1.4.1 版本无法缓存书籍
2. 在线阅读翻下一章总是会出现“内容为空”的情况

**重现步骤**
1. 打开IOS源阅读
2. 打开书架的书籍
3. 点击缓存
4. 下一章节

**期望结果**
1. 我想点击缓存的时候能够对书籍进行缓存。
2. 我希望在进入下一章节的时候能够去拉取章节内容，而不是直接显示“内容为空”
3. 以上问题都是在网络环境良好的情况下测试（5G移动网络、千兆电信宽带）

**截图**
无法缓存：
![c37bfa06189970679fdba375a776760](https://user-images.githubusercontent.com/22065342/135370529-73e22ba5-adeb-461d-89e6-6c45f41af8a0.jpg)
内容为空：
![a7e2c90797e310cbf546004b89d1bbc](https://user-images.githubusercontent.com/22065342/135370621-4c6bbdb5-ede4-463a-92ae-014a5d9d3837.jpg)
![edcb4f15547caeac405666b758deac2](https://user-images.githubusercontent.com/22065342/135370632-df42e117-b325-4e9a-99ea-82a4958cb911.jpg)

**测试环境**
 - 设备型号: [iPhone12]
 - 系统: [iOS14.2.1]
 - 书源: schema: [yuedu://book/open?src=aHR0cDovL3d3dy56d2R1eHMuY29tLzUyXzUyMTQ1Lw==]
 - 版本: [1.4.1]

**附加信息**
进入下一章，内容为空时点击刷新的按钮一两次可以加载出内容来。

**Comment by kaich** [comment]
没有内容会去啦，获取失败才会内容为空。能否获取到内容不是仅仅由你的网络状况决定的，网站不稳定同样可能获取不到。请先检查源网站
