### ISSUE TITLE
无法翻页看漫画（全屏）

### ISSUE THREAD

**Issue by song-zi** [kaich/Yuedu#51]
**功能详细描述.**
目前，看漫画有两种模式，
1常规的看书。可以翻页，但是图片是嵌入书页，相当于多了一大块黑边。
![QQ图片20211015161755](https://user-images.githubusercontent.com/33717168/137455411-dec9123a-8103-4947-bfc7-80f3305810c1.jpg)
![Uploading QQ图片20211015161755.jpg…]()

2漫画模式，瀑布流，只能竖着下滑，没有翻页。

因此产生的问题:
很多漫画没有页码。划来划去，容易看串页。
此外，点击翻页由与漫画实际大小不一致，看几页就需要调整一下高度。

**描述你想要的解决方案**
在正常的看书模式下，如果将图片放大填充整书页，即可去掉屏幕右侧留白，充分利用屏幕。

**附加信息**
并不是很重要的功能，大佬有空的时候看看吧。
顺便感谢大佬开发这个app，太好用了。

**Comment by kaich** [comment]
进入全屏模式

**Comment by kaich** [comment]
@song-zi  已经有了， 这个你用最新版，把把对应书源改成`图片`类型，即可用新版的图片阅读器。提供了更加优秀和丝滑的阅读体验
