### ISSUE TITLE
安卓阅读备份导入ios源阅读失败

### ISSUE THREAD

**Issue by yiweiwang-yw** [kaich/Yuedu#55]
**问题描述**
您好，我试了一下把安卓端的zip备份文件导入到ios源阅读，出现恢复备份失败的情况。备份文件里有书源和之前放在书架上的书.我试过直接改名覆盖和把zip里同名文件覆盖，都不行 请问一下目前安卓导入ios段的正确方法应该是什么样的？谢谢

**重现步骤**
安卓端备份生产zip
导入iphone
1. 直接覆盖后iphone导入备份失败
2. 把zip里同名文件覆盖导入备份失败

**测试环境**
 - 设备型号: iphone 13 pro
 - 系统: IOS15.1
 - 书源: 来自备份
 - 版本: 1.4.2

**附加信息**
在这里添加关于这个问题的其他内容。

> 请按照模板详细描述问题的内容，否则问题难以理解和重现，不会对此问题进行任何回复

**Comment by kaich** [comment]
设置 -> 备份/恢复 -> 点击恢复 -> 选择备份zip文件 -> 恢复完成

**Comment by yiweiwang-yw** [comment]
![image](https://user-images.githubusercontent.com/81563224/138437687-7d0e1f6f-d76e-490a-b4a6-b846c9bd6ca9.png)
您好，我是按照您这样的步骤的，但是显示恢复备份失败

**Comment by yiweiwang-yw** [comment]
[backup2021-10-22.zip](https://github.com/kaich/Yuedu/files/7396323/backup2021-10-22.zip)
这个是安卓端的备份文件

**Comment by kaich** [comment]
是用的阅读3.0吧？

**Comment by yiweiwang-yw** [comment]
是的，安卓的阅读版本是3.21.041610

**Comment by kaich** [comment]
安卓更新到最新的，然后导出。再恢复应该就可以了
