### ISSUE TITLE
内置字体名称错误

### ISSUE THREAD

**Issue by airinghost** [kaich/Yuedu#56]
**问题描述**
源阅读内置了 屏显臻宋（Clear Han Serif），但是在字体列表其名称显示为了 ClearlHanSerif（多了一个字母 l ）

**重现步骤**
1. 打开 任意一本书籍
2. 点击屏幕中央区域 呼出菜单
3. 点击弹出菜单界面右下角的 设置
4. 点击弹出二级菜单的 字体
5. 往下翻，就能看见该字体的名称了

**期望结果**
1. 修正字体名称
2. 对于中文字体，显示其中文名称更利于用户识别使用

**测试环境**
 - 设备型号: [iPhone SE 2020]
 - 系统: [iOS 15.1]
 - 版本: [V1.4.3]

**Comment by kaich** [comment]
你字体文件用的什么名字，上面就显示的什么名字。

**Comment by airinghost** [comment]
> 你字体文件用的什么名字，上面就显示的什么名字。

嗷，可它是软件内置的，不是我手动导入的。因为在字体列表中，内置的字体左滑只能选择复制名称，无法删除。
所以我刚刚又看了一下，左滑复制出来的名称是正确的 Clear Han Serif，但在列表中它确实多了一个字母 l。

**Comment by kaich** [comment]
这是自带的？我设备里面没看到这个字体啊！

**Comment by airinghost** [comment]
> 这是自带的？我设备里面没看到这个字体啊！

我截个图：

![E9523DDD-0633-4A8B-84B1-7320E6877175](https://user-images.githubusercontent.com/78188675/142578603-2395f901-7481-431c-b2dd-0e9cd041926b.jpeg)

**Comment by airinghost** [comment]
解决了：我把字体列表顶部的自定义导入字体删掉后，下面这个地方的字体也消失了... 

😂为啥导入一款字体它会在两个地方显示呀？
