### ISSUE TITLE
自动滚动调节成上下滚动会出现很诡异的问题

### ISSUE THREAD

**Issue by eachann1024** [kaich/Yuedu#60]
这个自动滚动 太离谱了吧
怎么背景图和低栏都一起滚动了

一直都是最新的tf版本，正式版也有这个问题
![52F3A935-D4F5-4361-BEF4-7D8C837FA3E2](https://user-images.githubusercontent.com/43348055/143930591-605a2fa0-d8b1-4a99-853b-95ebb9077c38.png)

**Comment by kaich** [comment]
不都写了测试么

**Comment by eachann1024** [comment]
> 不都写了测试么

知道是测试，我是特地上来反馈这个问题了，可能说的比较夸张

**Comment by eachann1024** [comment]
继续跟进一下这个问题

目前上面说的问题是已经得到解决了
