### ISSUE TITLE
反馈一个关于滚动翻页的bug

### ISSUE THREAD

**Issue by eachann1024** [kaich/Yuedu#61]
因为不是疑难杂症，只要简单的设置成竖屏就会出现的问题，我就不按照模板来了

竖屏之后小说的内容不会受到页首和页尾设置的边距影响
![7A9171F7-328E-48A6-8D3D-2D954073DF3D](https://user-images.githubusercontent.com/43348055/143931128-6f06360d-53d3-4b3f-bcba-0295406aaf5a.png)

而在其他模式下是正常的，这是无动画
![FA8BA61C-FDBC-4158-A9ED-404EE28B1D80](https://user-images.githubusercontent.com/43348055/143931382-71795f88-cd54-4500-9174-ea7d835c8c1b.png)

希望作者在有时间的时候修复一下

**Comment by kaich** [comment]
就是这样的，全屏滚动设置的是页面之间的间距
