### ISSUE TITLE
反馈个仿真动画翻页效果存在的问题

### ISSUE THREAD

**Issue by eachann1024** [kaich/Yuedu#62]
如果设置了全屏点击下一页的时候从左边拖动屏幕还是能够跳转到上一页（这个逻辑没问题），但是如果你用的仿真动画的话你看不出来是返回了上一页，因为他的动画还是下一页的动画

**Comment by kaich** [comment]
试了下并无你说的问题啊，滑动效果是跟手的啊。怎么可能你手在左边，翻页效果在右边

**Comment by eachann1024** [comment]
这次去看已经没这个问他了
