### ISSUE TITLE
请问能否支持直接调用[讯飞语记]App的离线TTS引擎

### ISSUE THREAD

**Issue by kuroyukihime0** [kaich/Yuedu#63]
**功能详细描述.**
朗读能否支持直接调用讯飞语记的本地TTS引擎,听下来还是讯飞的离线引擎合成出来最舒服
目前iOS上唯一支持的应该是[多看阅读], 是通过"打开一次讯飞语记",之后就可以直接调用讯飞语记的引擎了,不知道是商业方案还是开放的接口

**附加信息**
![B252DED78A29729C1F44E8A7C650704F](https://user-images.githubusercontent.com/7975549/144210195-fe5130be-ecff-49d0-90af-0b605a963660.jpg)

**Comment by kaich** [comment]
语记都下架了...
