### ISSUE TITLE
请问能否支持微软azure的tts服务

### ISSUE THREAD

**Issue by Jarvis110469** [kaich/Yuedu#64]
**功能详细描述.**
微软的tts 声音自然甜美，语气断句和词句判断都是顶级的。

**描述你想要的解决方案**
能像支持阿里的tts一样，能让用户自己配置就很好了，微软的声音真的很棒

**附加信息**
(https://azure.microsoft.com/zh-cn/services/cognitive-services/text-to-speech/)

**Comment by tzrl** [comment]
严重同意，听书功能强烈需求

**Comment by kaich** [comment]
请提供所有需要的配置参数

**Comment by Jarvis110469** [comment]
> 请提供所有需要的配置参数
适配文档如下：
https://docs.microsoft.com/zh-cn/azure/cognitive-services/speech-service/get-started-text-to-speech?tabs=script%2Cwindowsinstall&pivots=programming-language-csharp
参数主要有三个
1:key
2:语言
3:想要的声音
static async Task SynthesizeAudioAsync()
{
    var config = SpeechConfig.FromSubscription("<paste-your-speech-key-here>", "<paste-your-speech-location/region-here>");
    // Note: if only language is set, the default voice of that language is chosen.
    config.SpeechSynthesisLanguage = "<your-synthesis-language>"; // e.g. "de-DE"
    // The voice setting will overwrite language setting.
    // The voice setting will not overwrite the voice element in input SSML.
    config.SpeechSynthesisVoiceName = "<your-wanted-voice>";
}

**Comment by kaich** [comment]
@fanxinghaoyue0 需要的是key等那些参数值，直接填入即可测试！

**Comment by Jarvis110469** [comment]
key: b1396c7fd39544db99f95e387009fd14
区域：eastasia
语言
Chinese (Mandarin, Simplified)
语音
Xiaoxiao (Neural) - 晓晓
说话风格
General
语速: 1.00
音调: 0.00

**Comment by kaich** [comment]
@fanxinghaoyue0 好的，等下个版本应该会支持

**Comment by dragonoire** [comment]
源阅读自带的语言都无法使用！安卓上用得是微软小小！

**Comment by kaich** [comment]
> 源阅读自带的语言都无法使用！安卓上用得是微软小小！

@dragonoire 没看懂， 源阅读就系统是自带的，你手机上不能用？新手必读里面都有写得很清楚了。

**Comment by dragonoire** [comment]
> > 源阅读自带的语言都无法使用！安卓上用得是微软小小！
> 
> @dragonoire 没看懂， 源阅读就系统是自带的，你手机上不能用？新手必读里面都有写得很清楚了。

开启语音阅读后默认语音可以用.选其他语音人都是一个小女孩的声音.试过，语音管理删除所有语音，然后重置默认.清空所有语音，倒入某语音源.重新安装app恢复数据.上面这些操作都不管用.我怀疑不是bug就是我导入的语音也是有问题的！我试试看能不能找到可以用的语音.

**Comment by dragonoire** [comment]
![0EFC55F2-AF12-4885-8A0C-0D93CF6AE976](https://user-images.githubusercontent.com/50920496/147615683-65766800-a1d8-4eec-abee-c9cbaeb7d229.png)
设置完后在调试里面能正常阅读.到了小说里面怎么没有反应了？

**Comment by kaich** [comment]
@dragonoire 好的，但请不要用别人的Key.  此Key是提供调试测试使用。

@fanxinghaoyue0 测试无问题后，请立即更改你的Key，避免他人通过此处共用你的Key，造成你不必要的经济损失。

**Comment by Jarvis110469** [comment]
> @dragonoire 好的，但请不要用别人的Key. 此Key是提供调试测试使用。
> 
> @fanxinghaoyue0 测试无问题后，请立即更改你的Key，避免他人通过此处共用你的Key，造成你不必要的经济损失。

已更换 谢谢开发者的辛苦工作
