### ISSUE TITLE
请问是否有导入样式的配置文档说明

### ISSUE THREAD

**Issue by likeTianDian** [kaich/Yuedu#69]
之前用起点看书感觉背景文字什么很舒服，想导入到阅读来，但是样式有点多，手动配置太麻烦，就想用网络导入，但是没找到相关配置的说明文档。
试过在软件配置然后分享，但是分享的是个.srs文件，打开后是乱码。本人在网上也没找到别人分享的模板。

**Comment by kaich** [comment]
没有网络导入功能，一般样式都包含有图片、字体等，阅读样式文件过大。自己做或者使用别人做好分享的。
