### ISSUE TITLE
添加本地书籍搞不清目录的话，整个书籍都添加失败了

### ISSUE THREAD

**Issue by mGitup** [kaich/Yuedu#70]
**问题描述**
我添加本地txt文件，但是源阅读获取目录失败，有一个把前面说明当成了目录，有一个一个字都没有显示。
我觉得失败的原因可能是，文件最开头一部分说明也写了部分目录，特别是修改版经常有这个的。
一个字都没显示那个，前面也有作品、作者、内容、简介、补充等说明。

**重现步骤**
1. 在qq选择用源阅读打开txt文件
2. 书籍导入
3. 查看目录，把开头说明部分当成了目录
4. 目录以外的就获取不到

**期望结果**
我觉得，硬要搞出目录确实会挺麻烦，所以希望就算获取不到或者获取到错误目录，也能显示整本书所有文字

**截图**
![IMG_0241](https://user-images.githubusercontent.com/88976609/148875966-cd9a6016-d3a8-4df7-878e-4ce513793cb2.PNG)

**测试环境**
 - 设备型号: [e.g. iPhone12]
 - 系统: [e.g. iOS15.2]
 - 书源: 本地
 - 版本: [1.4.7]

**Comment by kaich** [comment]
用新版

**Comment by mGitup** [comment]
> 用新版

新版目录解析确实好一些，虽然有些把内容也当目录了。但我希望没有目录也能显示全文的那种，解析不出目录就全部显示。
或者加个按钮，“目录有异常”，然后点这个就可以显示全文。作者大大，你觉得怎么样呢？

**Comment by kaich** [comment]
一章太多字，动辄就大几百页，分页得很久，体验非常不好！😓  这种没有分章节的巨大段文本，建议你直接用专注于本地阅读的阅读器，这样体验会更好。针对这种情况，对源阅读而言优先级很低，也许以后实在空闲才会去处理这种情况。目前并没有时间去处理非核心功能。
