### ISSUE TITLE
有翻页动画时切换页面组建栏同时翻页

### ISSUE THREAD

**Issue by WeathyPanda** [kaich/Yuedu#71]
**问题描述**
在选择平移翻页效果时时，左滑翻页、右滑翻页的时候顶部和底部组建栏也会同时移动。

**期望结果**
希望翻页时顶部、底部组建栏固定。

**截图**
![3BF1AE3B-C1C3-41F2-93A9-8BD63BAF1C63](https://user-images.githubusercontent.com/38719636/149632324-1f74bcfb-046c-4e96-b977-9cf6c3d98920.jpeg)

**测试环境**
 - 设备型号: [ iPhone 13 Pro]
 - 系统: [iOS 15.2.1]
 - 版本: [V1.4.8]

**Comment by kaich** [comment]
不不不，就是这样设计的
