### ISSUE TITLE
增加阅读时屏幕常亮或者亮屏时间可配

### ISSUE THREAD

**Issue by ilylia** [kaich/Yuedu#80]
**功能详细描述.**
正在看小说时，偶尔搞个别的事，再回来就又锁了需要重新解锁，有点麻烦。

**描述你想要的解决方案**
增加阅读时屏幕常亮或者亮屏时间可配，比如5分钟后再息屏之类的。

**附加信息**
无。

**Comment by kaich** [comment]
设置里面有

**Comment by ilylia** [comment]
好的，找到了，要在看书界面下找设置然后界面最上面，多谢
