### ISSUE TITLE
请问一下，网页提示那个书详情进入阅读模式是怎样实现的？

### ISSUE THREAD

**Issue by yueyuedede1** [kaich/Yuedu#86]
作者可以指导一下吗？

**Comment by kaich** [comment]
这个可就太复杂了。

找到要显示的主题，用更加友好的UI显示出来。

原理就是这么个原理，实现起来就很复杂了。

建议参考其它UC、夸克、Safari等浏览器阅读模式功能！

**Comment by yueyuedede1** [comment]
你好，你这话就像没说一样，怎么获取和解析内容呢 。

**Comment by kaich** [comment]
参考其它浏览器呢，去搜一些开源的类似功能的插件啊，看看别人怎么写的！至于效果就慢慢调啊！

**Comment by yueyuedede1** [comment]
就是找不到才问你啊~~

**Comment by yueyuedede1** [comment]
> 参考其它浏览器呢，去搜一些开源的类似功能的插件啊，看看别人怎么写的！至于效果就慢慢调啊！

哪些开源插件啊  给点思路
