### ISSUE TITLE
Azure 获取朗读音频返回数据为空

### ISSUE THREAD

**Issue by moriwang** [kaich/Yuedu#88]
**问题描述**
Azure语音调试无音频返回。

**重现步骤**
1. Go to 语音管理
2. Click on 编辑语音源，点击调试
3. See error

**期望结果**
几天前还能正确运行，已排除网络环境问题。

**截图**
![image](https://user-images.githubusercontent.com/9151525/160226273-b034772c-88d5-42cc-82f6-9ac81584aedb.png)

**测试环境**
 - 设备型号: [e.g. iPhone13 mini]
 - 系统: [e.g. iOS15.4]
 - 版本: [e.g. v 1.5.0]

**Comment by yefeiyu** [comment]
> **问题描述** Azure语音调试无音频返回。
> 
> **重现步骤**
> 
> 1. Go to 语音管理
> 2. Click on 编辑语音源，点击调试
> 3. See error
> 
> **期望结果** 几天前还能正确运行，已排除网络环境问题。
> 
> **截图** ![image](https://user-images.githubusercontent.com/9151525/160226273-b034772c-88d5-42cc-82f6-9ac81584aedb.png)
> 
> **测试环境**
> 
> * 设备型号: [e.g. iPhone13 mini]
> * 系统: [e.g. iOS15.4]
> * 版本: [e.g. v 1.5.0]

请问您这个问题解决了吗？我也出现这个问题。
今天我是新安装。第一次用。完全一样“为空”。

**Comment by moriwang** [comment]
@yefeiyu 检查一下 Subscription-Key 吧，可能失效了或者额度用超了。
