### ISSUE TITLE
咦，感觉少了点阅读味

### ISSUE THREAD

**Issue by eachann1026** [kaich/Yuedu#9]
>  滚动阅读下不能点击翻页了（这个太重要了呀）
设置界面风格混搭了

不过话说阅读上了ios端，其他阅读软件还有活路吗？

**Comment by kaich** [comment]
滚动点击可以翻页啊。 这边测试没有问题。

下个TF版会修复比较多的问题和细节.

设置界面不重要的现在没空花很多时间再上面。先能正常使用，以后再增加细节和特色功能！

**Comment by eachann1026** [comment]
> 要设置成点击全屏自定义，再点设置自定义区域最后点一下完成才生效

设置的时候顺便发现了一些bug
* 更换字体不生效
* 自定义布局不生效
都是设置成滚动才发现的问题

**Comment by kaich** [comment]
已修复

**Comment by eachann1026** [comment]
修复个鬼啊
https://share.icloud.com/photos/0s4jcC1HMkfSQ4zp6FSYqBNYg

**Comment by eachann1026** [comment]
> 问个问题，怎么样才可以实现点击全屏切换下一页，点击正中间弹出菜单


![E5A0D05E-13DD-4E6A-857B-9B41FDB8BE95](https://user-images.githubusercontent.com/43348055/120514176-980d0900-c3ff-11eb-8672-444addd9822a.png)

**Comment by kaich** [comment]
@eachann1026 你发的视频是什么？ 是你发的两个问题？如果不同问题请详细描述反馈

**Comment by eachann1026** [comment]
新发现的bug发了新的Issue了，楼上截图是想问另一个问题，我记得用安卓的时候阅读2.x的时候是可以这样操作的

> 点击`屏幕中间` 会显示菜单，设置了`全屏下一页`以后，点击`左右两边`都是下一页
