### ISSUE TITLE
获取朗读音频返回数据为空

### ISSUE THREAD

**Issue by yefeiyu** [kaich/Yuedu#95]
**问题描述**
对错误的清晰而简明的描述。

**重现步骤**
1. Go to '语音源调试'
2. Click on 'bug'
3. Scroll down to ''
开始解析
获取朗读音频返回数据为空
解析完成

**期望结果**
解决bug

**截图**

**测试环境**
 - 设备型号: [e.g. iPhone8p，Jailbreak]
 - 系统: [e.g. iOS14.3]
 - 书源: [txt]
 - 版本: [e.g. 1.50, download from QQ群，非appstore下载]

**附加信息**
Azure添加的TTS。已填写好了key等。

> 请按照模板详细描述问题的内容，否则问题难以理解和重现，不会对此问题进行任何回复
![IMG_7244](https://user-images.githubusercontent.com/4845104/163127492-350ddd15-b1d1-463e-bed9-a4c43dd1dacc.PNG)
![IMG_7243](https://user-images.githubusercontent.com/4845104/163127532-129fec04-0c3d-49b2-a26e-5ed9bf7e1117.PNG)

**Comment by iamsweet** [comment]
一样的问题

**Comment by moriwang** [comment]
我上月遇到问题就是额度超了，免费额度只用了七八天。建议你去 Azure console 检查一下过去 30 天已用的 Synthesized Characters 总和，或者拿个 api 工具自己测试一下，是否返回数据正常。

**Comment by yefeiyu** [comment]
> 我上月遇到问题就是额度超了，免费额度只用了七八天。建议你去 Azure console 检查一下过去 30 天已用的 Synthesized Characters 总和，或者拿个 api 工具自己测试一下，是否返回数据正常。

我这是新申请的azure
可能是“源阅读”是越狱安装、以前从没注册过源阅读的原因？

**Comment by kaich** [comment]
注意检查账号的region是否和配置对应、流量是否用完

**Comment by yefeiyu** [comment]
> 注意检查账号的region是否和配置对应、流量是否用完

惭愧，region使用了默认的。没细看
多谢楼上
